In [1]:
import pandas as pd
from src.transform import get_device_data,get_all_devices_data,transform_columns_air_w

## indoor data

In [2]:
indoor_devices = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
referent_indoor = 316

In [3]:
df_indoor = get_all_devices_data(indoor_devices,indoor=True)
df_indoor = transform_columns_air_w(df_indoor,indoor=True)
df_indoor

,co2,tvoc,co,pm_1.0,pm_2.5,pm_10,temperature,humidity,pressure,device_id,NO2,O3,NH3,sensor
datetime,,,,,,,,,,,,,,
2024-10-16 05:00:43,657.32,0.00,0.5,2.15,2.27,2.24,26.60,33.0,1010.26,2.0,NaN,NaN,NaN,air_wings_indoor
2024-10-16 05:01:43,657.32,0.00,0.5,2.15,2.25,2.23,26.60,33.0,1010.28,2.0,NaN,NaN,NaN,air_wings_indoor
2024-10-16 05:02:43,657.31,0.00,0.5,2.13,2.24,2.22,26.60,33.0,1010.30,2.0,NaN,NaN,NaN,air_wings_indoor
2024-10-16 05:03:43,657.31,0.00,0.5,2.05,2.15,2.13,26.59,33.0,1010.30,2.0,NaN,NaN,NaN,air_wings_indoor
2024-10-16 05:04:43,657.31,0.00,0.5,2.00,2.11,2.09,26.59,33.0,1010.31,2.0,NaN,NaN,NaN,air_wings_indoor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-31 11:22:28,677.08,193.34,0.5,24.16,25.89,26.30,25.06,42.0,1017.01,15.0,NaN,NaN,NaN,air_wings_indoor
2024-10-31 11:23:28,680.50,194.74,0.5,24.12,25.87,26.32,25.11,42.0,1017.01,15.0,NaN,NaN,NaN,air_wings_indoor
2024-10-31 11:24:28,674.21,193.52,0.5,24.12,25.83,26.22,25.16,42.0,1017.00,15.0,NaN,NaN,NaN,air_wings_indoor
2024-10-31 11:25:28,676.64,194.44,0.5,23.94,25.56,25.87,25.19,42.0,1017.00,15.0,NaN,NaN,NaN,air_wings_indoor
2024-10-31 11:26:28,679.47,195.62,0.5,23.95,25.51,25.74,25.24,42.0,1017.00,15.0,NaN,NaN,NaN,air_wings_indoor

### ref sensor

In [4]:
df_indoor_ref = get_device_data(316,indoor=True)
df_indoor_ref = transform_columns_air_w(df_indoor_ref,indoor=True)
df_indoor_ref["sensor"] = "air_wings_indoor_ref"

## outdoors

In [5]:
outdoor_devices = [103,104,105,106,107,108,109,110,111]
referent_indoor = 402

In [6]:
df_outdoor = get_all_devices_data(outdoor_devices,indoor=False)
df_outdoor = transform_columns_air_w(df_outdoor,indoor=False)
df_outdoor

,no2,o3,so2,co,pm_1.0,pm_2.5,pm_10,no,temperature,humidity,pressure,noise,device_id,sensor
datetime,,,,,,,,,,,,,,
2024-10-29 14:16:53,0.00,30.12,647.64,3588.43,15.95,28.15,81.59,99.68,28.19,34.61,1013.0,75.0,103.0,air_wings_outdoor
2024-10-29 14:47:30,0.00,37.00,141.36,3055.26,1.77,8.71,18.11,33.01,32.13,28.09,1013.0,76.0,103.0,air_wings_outdoor
2024-10-29 15:17:53,2.01,39.98,50.04,1493.17,1.15,8.05,15.62,20.23,34.03,24.98,1013.0,76.0,103.0,air_wings_outdoor
2024-10-29 15:48:18,7.60,41.09,36.48,805.49,1.62,8.48,16.45,14.10,31.87,27.03,1013.0,76.0,103.0,air_wings_outdoor
2024-10-29 16:18:43,12.35,41.83,30.60,516.30,2.63,9.57,22.82,9.35,26.91,33.90,1013.0,76.0,103.0,air_wings_outdoor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-31 09:51:53,16.22,41.84,11.55,310.62,6.14,10.82,19.47,1.77,6.12,83.48,1016.0,46.0,111.0,air_wings_outdoor
2024-10-31 10:22:21,16.10,41.86,11.20,282.63,5.16,9.97,17.87,1.76,6.97,80.31,1015.0,47.0,111.0,air_wings_outdoor
2024-10-31 10:52:43,15.98,41.85,11.06,273.19,5.84,10.56,18.92,1.78,7.84,77.63,1016.0,47.0,111.0,air_wings_outdoor
2024-10-31 11:23:06,15.94,41.83,11.34,279.48,6.45,11.07,20.14,1.80,8.54,76.76,1016.0,47.0,111.0,air_wings_outdoor
2024-10-31 11:53:29,16.03,41.87,11.34,304.65,10.22,13.84,25.80,1.83,8.98,76.31,1016.0,47.0,111.0,air_wings_outdoor

### ref sensor

In [7]:
df_outdoor_ref = get_device_data(referent_indoor,indoor=False)
df_outdoor_ref = transform_columns_air_w(df_outdoor_ref,indoor=False)
df_outdoor_ref["sensor"] = "air_wings_outdoor_ref"

## Full airwings data

In [8]:
full_air_wings = pd.concat([df_indoor,df_indoor_ref,df_outdoor,df_outdoor_ref])
full_air_wings.to_csv("data/clean_data/airwings.csv")