In [15]:
import pandas as pd
from src.transform import get_device_data,get_all_devices_data,transform_columns_air_w

## indoor data

In [16]:
indoor_devices = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
referent_indoor = 316

In [17]:
df_indoor = get_all_devices_data(indoor_devices,indoor=True)
df_indoor = transform_columns_air_w(df_indoor,indoor=True)
df_indoor

,co2,tvoc,co,pm_1.0,pm_2.5,pm_10,temperature,humidity,pressure,device_id,sensor
datetime,,,,,,,,,,,
2024-10-16 05:00:43,657.32,0.0,0.5,2.15,2.27,2.24,26.60,33.0,1010.26,2.0,air_wings_indoor
2024-10-16 05:01:43,657.32,0.0,0.5,2.15,2.25,2.23,26.60,33.0,1010.28,2.0,air_wings_indoor
2024-10-16 05:02:43,657.31,0.0,0.5,2.13,2.24,2.22,26.60,33.0,1010.30,2.0,air_wings_indoor
2024-10-16 05:03:43,657.31,0.0,0.5,2.05,2.15,2.13,26.59,33.0,1010.30,2.0,air_wings_indoor
2024-10-16 05:04:43,657.31,0.0,0.5,2.00,2.11,2.09,26.59,33.0,1010.31,2.0,air_wings_indoor
...,...,...,...,...,...,...,...,...,...,...,...
2024-10-20 23:55:11,967.76,135.0,0.5,36.75,39.23,39.68,24.16,42.0,1018.55,15.0,air_wings_indoor
2024-10-20 23:56:11,968.69,135.0,0.5,37.23,39.65,40.00,24.15,42.0,1018.55,15.0,air_wings_indoor
2024-10-20 23:57:11,969.33,135.0,0.5,37.34,39.65,39.87,24.15,42.0,1018.54,15.0,air_wings_indoor
2024-10-20 23:58:11,969.09,135.0,0.5,37.34,39.69,39.96,24.15,42.0,1018.54,15.0,air_wings_indoor
2024-10-20 23:59:11,969.93,135.0,0.5,37.14,39.49,39.78,24.15,42.0,1018.54,15.0,air_wings_indoor

### ref sensor

In [18]:
df_indoor_ref = get_device_data(316,indoor=True)
df_indoor_ref = transform_columns_air_w(df_indoor_ref,indoor=True)
df_indoor_ref["sensor"] = "air_wings_indoor_ref"

## outdoors

In [19]:
outdoor_devices = [103,104,105,106,107,108,109,110,111]
referent_indoor = 402

In [20]:
df_outdoor = get_all_devices_data(outdoor_devices,indoor=False)
df_outdoor = transform_columns_air_w(df_outdoor,indoor=False)
df_outdoor

,no2,o3,so2,co,pm_1.0,pm_2.5,pm_10,no,temperature,humidity,pressure,noise,device_id,sensor
datetime,,,,,,,,,,,,,,
2024-10-16 05:00:22,15.43,42.25,7.22,244.22,1.70,9.52,20.55,2.30,18.12,53.24,1013.0,56.0,104.0,air_wings_outdoor
2024-10-16 05:01:34,15.45,42.25,7.33,243.26,1.70,9.52,20.55,2.30,18.12,53.35,1013.0,57.0,104.0,air_wings_outdoor
2024-10-16 05:02:46,15.43,42.25,7.38,244.22,1.70,9.52,20.55,2.27,18.12,53.26,1013.0,55.0,104.0,air_wings_outdoor
2024-10-16 05:04:28,15.42,42.25,7.16,243.06,1.70,9.52,20.55,2.28,18.12,53.18,1013.0,55.0,104.0,air_wings_outdoor
2024-10-16 05:05:40,15.43,42.25,7.22,244.61,1.70,9.52,20.55,2.31,18.10,53.15,1013.0,56.0,104.0,air_wings_outdoor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-20 21:57:53,16.00,42.36,11.50,356.19,3.11,9.63,18.96,1.61,11.25,58.45,1014.0,48.0,109.0,air_wings_outdoor
2024-10-20 22:28:02,16.84,42.37,11.85,419.38,3.72,10.21,20.53,1.83,10.87,59.85,1014.0,47.0,109.0,air_wings_outdoor
2024-10-20 22:58:10,16.36,42.32,11.78,397.16,3.47,9.96,19.69,1.59,10.77,60.09,1014.0,46.0,109.0,air_wings_outdoor
2024-10-20 23:28:15,16.44,42.29,12.83,474.58,4.69,11.04,23.09,1.94,10.55,60.91,1014.0,46.0,109.0,air_wings_outdoor
2024-10-20 23:58:20,16.50,42.28,13.18,491.60,3.84,10.33,20.92,2.66,10.30,61.33,1014.0,45.0,109.0,air_wings_outdoor

### ref sensor

In [22]:
df_outdoor_ref = get_device_data(referent_indoor,indoor=False)
df_outdoor_ref = transform_columns_air_w(df_outdoor_ref,indoor=False)
df_outdoor_ref["sensor"] = "air_wings_indoor_ref"

## Full airwings data

In [24]:
full_air_wings = pd.concat([df_indoor,df_indoor_ref,df_outdoor,df_outdoor_ref])
full_air_wings.to_csv("data/clean_data/airwings.csv")