In [3]:
import pandas as pd
import gdown
import os

## Download data

In [14]:
# Google Drive URLs
url_inbiot = 'https://drive.google.com/uc?id=1H330C2-_H52RnGUyXdWjvJ9ZF5Ai94Fc'
url_kaiterra = 'https://drive.google.com/uc?id=1taSJBN8851szNyqIkvjTTo-WoI27AP6w'
url_LS_168 = 'https://drive.google.com/uc?id=1dBaHyOHIQEWn40M1g-NxFFKtmVlZYE8v'
url_LS_169 = 'https://drive.google.com/uc?id=1H3C6MarJOyPo7NSR_jNlegtC-YtEgY5J'
url_smart_s = 'https://drive.google.com/uc?id=1WhS5kb367pDKGHrR4pxmnCUVj7xqW5ij'
url_ref = 'https://drive.google.com/uc?id=1-NsVMmtLzrokCv5Sb7qqT_jkscCrcCK-'

# Create folder for data
os.makedirs('data', exist_ok=True)
os.makedirs('data/clean_data', exist_ok=True)


# Output paths
output_inbiot = 'data/Inbiot.csv'
output_kaiterra = 'data/Kaiterra.csv'
output_ls_168 = 'data/ls_168.csv'
output_ls_169 = 'data/ls_169.csv'
output_smart_sense = 'data/smart_sense.csv'
output_ref_data = 'data/ref_data.csv'


# Download each file to the specified location
gdown.download(url_inbiot, output_inbiot, quiet=False)
gdown.download(url_kaiterra, output_kaiterra, quiet=False)
gdown.download(url_LS_168, output_ls_168, quiet=False)
gdown.download(url_LS_169, output_ls_169, quiet=False)
gdown.download(url_smart_s, output_smart_sense, quiet=False)
gdown.download(url_ref, output_ref_data, quiet=False)

Downloading...
From: https://drive.google.com/uc?id=1H330C2-_H52RnGUyXdWjvJ9ZF5Ai94Fc
To: /home/usr1_tt/collocation_study/data/Inbiot.csv
100%|██████████| 195k/195k [00:00<00:00, 3.50MB/s]
Downloading...
From: https://drive.google.com/uc?id=1taSJBN8851szNyqIkvjTTo-WoI27AP6w
To: /home/usr1_tt/collocation_study/data/Kaiterra.csv
100%|██████████| 1.67M/1.67M [00:00<00:00, 12.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1dBaHyOHIQEWn40M1g-NxFFKtmVlZYE8v
To: /home/usr1_tt/collocation_study/data/ls_168.csv
100%|██████████| 63.4M/63.4M [00:00<00:00, 80.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1H3C6MarJOyPo7NSR_jNlegtC-YtEgY5J
To: /home/usr1_tt/collocation_study/data/ls_169.csv
100%|██████████| 42.0M/42.0M [00:01<00:00, 39.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1WhS5kb367pDKGHrR4pxmnCUVj7xqW5ij
To: /home/usr1_tt/collocation_study/data/smart_sense.csv
100%|██████████| 2.13M/2.13M [00:00<00:00, 15.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-NsVMmtLzrokCv5Sb7qqT_jkscCrcCK-
To: /home/usr1_tt/collocation_study/data/ref_data.csv
100%|██████████| 5.82M/5.82M [00:00<00:00, 53.4MB/s]

'data/ref_data.csv'

### Thinnect

In [ ]:

url_thinnect_co2_1 = 'https://drive.google.com/uc?id=1vKxIuJFzGx5MYkL0VeM6DIhrqBhbTfVd'
url_thinnect_o3_1 = 'https://drive.google.com/uc?id=1oXbvoNHpR1xDsiRGvzQoirRbbPN-jAbi'
url_thinnect_pm1_1 = 'https://drive.google.com/uc?id=1J43tdGDXpvLFzukTs7OT7R9AJq7QaRG2'
url_thinnect_pm2_5_1 = 'https://drive.google.com/uc?id=1ixPOJ64Ys41uy_hBthkeJ2KtagRUfFVv'
url_thinnect_pm10_1 = 'https://drive.google.com/uc?id=1S7N113sBwYHUuDsnqWRir1cnXWMHRDlL'
url_thinect_rhr_1 = 'https://drive.google.com/uc?id=1Om6v-2nHa9OZt8wBFO8JrRPe5Bn4EiL3'
url_thinect_tar_1 = 'https://drive.google.com/uc?id=1c5QRNKBCQRlaSVskHEoTfIxioIBRmZC4'
url_thinect_vocr_1 = 'https://drive.google.com/uc?id=1WvPPzenG76UFNn5I-XRuyZxsYun2E4_o'

url_thinnect_co2_2 = 'https://drive.google.com/uc?id=1fsUNAJux2ZmOrL26sLg_qBybNsb1aeNm'
url_thinnect_o3_2 = 'https://drive.google.com/uc?id=1rxcL7cphkS2lVzFuaSj_z9oXqfOFqIPx'
url_thinnect_pm1_2 = 'https://drive.google.com/uc?id=1clh9SjDhTFJcuM_64ZTXqcU1GkS34TbB'
url_thinnect_pm2_5_2 = 'https://drive.google.com/uc?id=1myEe9jh4BPabRoGiIH6TyQDeUjmy3O66'
url_thinnect_pm10_2 = 'https://drive.google.com/uc?id=1Vy5CDceL0nQ1SPKezyIDt7W7VoM5M_qi'
url_thinect_rhr_2 = 'https://drive.google.com/uc?id=1hImH6Gf3x-NnRwyy4ViNT0mztTqOUpDk'
url_thinect_tar_2 = 'https://drive.google.com/uc?id=1lxarIdh-QJr4km9vq_qAsjtiIey8kQBB'
url_thinect_vocr_2 = 'https://drive.google.com/uc?id=1tdGnJhpwZQYvwRv9rioZ_a7VvM4Z11Sl'

url_thinnect_co2_3 = 'https://drive.google.com/uc?id=1OrPdGIxFX75WzsmI69wa774pF9WckGoj'
url_thinnect_o3_3 = 'https://drive.google.com/uc?id=1fNU8Os2mSYAo_Se01kLwudAPUEP_wf9b'
url_thinnect_pm1_3 = 'https://drive.google.com/uc?id=1vqUQPKcnpf94HgvSj1JHNGHcQUPuNfAN'
url_thinnect_pm2_5_3 = 'https://drive.google.com/uc?id=16agFe-4l9V0vRhWmb9_aumM-LcQKfMc9'
url_thinnect_pm10_3 = 'https://drive.google.com/uc?id=15nTryD5DDfncW6jQ0kSzhJvLtzrEy6bN'
url_thinect_rhr_3 = 'https://drive.google.com/uc?id=1QlG_koBMMMzxfbaDvAN8fOFMKl9-uTnW'
url_thinect_tar_3 = 'https://drive.google.com/uc?id=1VfXwQiqka3wF3dWN7EN2ZjMVUD1-5B6x'
url_thinect_vocr_3 = 'https://drive.google.com/uc?id=1m9CWPU4rQk92jEmEPW9tzce6xlJT8_ms'

url_thinnect_co2_4 = 'https://drive.google.com/uc?id=1tiKiR_6VrqQZmpmAmPKIziPXrzhBgVv3'
url_thinnect_o3_4 = 'https://drive.google.com/uc?id=1P3JtIg1haqDnMJCNi-T58EXZXS5E2UVq'
url_thinnect_pm1_4 = 'https://drive.google.com/uc?id=1NbdAmcROlVLI8-aAti66E09sHuVRHxlB'
url_thinnect_pm2_5_4 = 'https://drive.google.com/uc?id=1F-00hze-6dyKLB9IgSKrJyZUjsYuwDd-'
url_thinnect_pm10_4 = 'https://drive.google.com/uc?id=1FhEdA0dySIycem0GUF58bXl7qY86oeYk'
url_thinect_rhr_4 = 'https://drive.google.com/uc?id=1cRo-5y5_RR4S8egkbCEgeTbLNiKsO20k'
url_thinect_tar_4 = 'https://drive.google.com/uc?id=1RA82x2XkwY6PUambOs8rfC_HdX3W_QsE'
url_thinect_vocr_4 = 'https://drive.google.com/uc?id=1xtccc3HemAhM02MdoLt1hKnb5zyDh_LA'

In [15]:

data = {
    "co2": [
        'https://drive.google.com/uc?id=1vKxIuJFzGx5MYkL0VeM6DIhrqBhbTfVd',
        'https://drive.google.com/uc?id=1fsUNAJux2ZmOrL26sLg_qBybNsb1aeNm',
        'https://drive.google.com/uc?id=1OrPdGIxFX75WzsmI69wa774pF9WckGoj',
        'https://drive.google.com/uc?id=1tiKiR_6VrqQZmpmAmPKIziPXrzhBgVv3'
    ],
    "o3": [
        'https://drive.google.com/uc?id=1oXbvoNHpR1xDsiRGvzQoirRbbPN-jAbi',
        'https://drive.google.com/uc?id=1rxcL7cphkS2lVzFuaSj_z9oXqfOFqIPx',
        'https://drive.google.com/uc?id=1fNU8Os2mSYAo_Se01kLwudAPUEP_wf9b',
        'https://drive.google.com/uc?id=1P3JtIg1haqDnMJCNi-T58EXZXS5E2UVq'
    ],
    "pm1": [
        'https://drive.google.com/uc?id=1J43tdGDXpvLFzukTs7OT7R9AJq7QaRG2',
        'https://drive.google.com/uc?id=1clh9SjDhTFJcuM_64ZTXqcU1GkS34TbB',
        'https://drive.google.com/uc?id=1vqUQPKcnpf94HgvSj1JHNGHcQUPuNfAN',
        'https://drive.google.com/uc?id=1NbdAmcROlVLI8-aAti66E09sHuVRHxlB'
    ],
    "pm2_5": [
        'https://drive.google.com/uc?id=1ixPOJ64Ys41uy_hBthkeJ2KtagRUfFVv',
        'https://drive.google.com/uc?id=1myEe9jh4BPabRoGiIH6TyQDeUjmy3O66',
        'https://drive.google.com/uc?id=16agFe-4l9V0vRhWmb9_aumM-LcQKfMc9',
        'https://drive.google.com/uc?id=1F-00hze-6dyKLB9IgSKrJyZUjsYuwDd-'
    ],
    "pm10": [
        'https://drive.google.com/uc?id=1S7N113sBwYHUuDsnqWRir1cnXWMHRDlL',
        'https://drive.google.com/uc?id=1Vy5CDceL0nQ1SPKezyIDt7W7VoM5M_qi',
        'https://drive.google.com/uc?id=15nTryD5DDfncW6jQ0kSzhJvLtzrEy6bN',
        'https://drive.google.com/uc?id=1FhEdA0dySIycem0GUF58bXl7qY86oeYk'
    ],
    "rhr": [
        'https://drive.google.com/uc?id=1Om6v-2nHa9OZt8wBFO8JrRPe5Bn4EiL3',
        'https://drive.google.com/uc?id=1hImH6Gf3x-NnRwyy4ViNT0mztTqOUpDk',
        'https://drive.google.com/uc?id=1QlG_koBMMMzxfbaDvAN8fOFMKl9-uTnW',
        'https://drive.google.com/uc?id=1cRo-5y5_RR4S8egkbCEgeTbLNiKsO20k'
    ],
    "tar": [
        'https://drive.google.com/uc?id=1c5QRNKBCQRlaSVskHEoTfIxioIBRmZC4',
        'https://drive.google.com/uc?id=1lxarIdh-QJr4km9vq_qAsjtiIey8kQBB',
        'https://drive.google.com/uc?id=1VfXwQiqka3wF3dWN7EN2ZjMVUD1-5B6x',
        'https://drive.google.com/uc?id=1RA82x2XkwY6PUambOs8rfC_HdX3W_QsE'
    ],
    "vocr": [
        'https://drive.google.com/uc?id=1WvPPzenG76UFNn5I-XRuyZxsYun2E4_o',
        'https://drive.google.com/uc?id=1tdGnJhpwZQYvwRv9rioZ_a7VvM4Z11Sl',
        'https://drive.google.com/uc?id=1m9CWPU4rQk92jEmEPW9tzce6xlJT8_ms',
        'https://drive.google.com/uc?id=1xtccc3HemAhM02MdoLt1hKnb5zyDh_LA'
    ]
}

In [16]:
os.makedirs('data/thinnect', exist_ok=True)

for key,values in data.items():
    os.makedirs(f'data/thinnect/{key}', exist_ok=True)  
    
    for index, url in enumerate(values):
        
        try:
            gdown.download(url,f'data/thinnect/{key}/{key}_{index}.csv', quiet=True)
            
        except Exception:
            print("problem with url:",url)

## Sensors data

### inbiot

* Data ranges from: **2024-10-11 : 2024-10-21**

In [26]:
df_inbiot = pd.read_csv('data/Inbiot.csv')

df_inbiot

,Date,Time,Temperature (°C),Humidity (%),CO2 (ppm),Formaldehyde (µg/m3),TVOC (Index),PM 1.0 (µg/m3),PM 4.0 (µg/m3),PM 10 (µg/m3),PM 2.5 (µg/m3)
0,2024-10-11,13:24:18,20.5,58.0,566.0,3.0,0.0,1.0,1.0,1.0,1.0
1,2024-10-11,13:33:57,21.0,58.0,528.0,11.0,87.0,1.0,1.0,1.0,1.0
2,2024-10-11,13:43:57,22.2,57.0,596.0,36.0,103.0,1.0,1.0,1.0,1.0
3,2024-10-11,13:44:34,22.7,57.0,675.0,42.0,103.0,1.0,1.0,1.0,1.0
4,2024-10-11,13:54:27,23.0,57.0,701.0,41.0,102.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
2877,2024-10-31,10:43:52,24.3,54.0,734.0,54.0,498.0,32.0,34.0,34.0,34.0
2878,2024-10-31,10:53:52,24.2,54.0,718.0,47.0,498.0,31.0,32.0,32.0,32.0
2879,2024-10-31,11:03:52,24.1,54.0,703.0,45.0,498.0,28.0,29.0,29.0,29.0
2880,2024-10-31,11:13:52,23.7,52.0,619.0,40.0,490.0,20.0,21.0,21.0,21.0
2881,2024-10-31,11:23:52,23.7,55.0,630.0,40.0,487.0,18.0,19.0,19.0,19.0

#### preprocessing

In [27]:
df_inbiot['Date'] = df_inbiot['Date'].astype(str)
df_inbiot['Time'] = df_inbiot['Time'].astype(str)

df_inbiot['datetime'] = pd.to_datetime(df_inbiot['Date'] + ' ' + df_inbiot['Time'], format='%Y-%m-%d %H:%M:%S')


df_inbiot.columns = (
    df_inbiot.columns
    .str.replace(r"\(.*?\)", "", regex=True)  
    .str.replace(r"\s+", "_", regex=True)     
    .str.rstrip("_")                          
    .str.lower()                              
)

df_inbiot["sensor"] = "inbiot"
print(df_inbiot.columns)
df_inbiot.drop(columns=["date","time"],inplace=True)

df_inbiot.set_index("datetime",inplace=True)

Index(['date', 'time', 'temperature', 'humidity', 'co2', 'formaldehyde',
       'tvoc', 'pm_1.0', 'pm_4.0', 'pm_10', 'pm_2.5', 'datetime', 'sensor'],
      dtype='object')

In [28]:
df_inbiot

,temperature,humidity,co2,formaldehyde,tvoc,pm_1.0,pm_4.0,pm_10,pm_2.5,sensor
datetime,,,,,,,,,,
2024-10-11 13:24:18,20.5,58.0,566.0,3.0,0.0,1.0,1.0,1.0,1.0,inbiot
2024-10-11 13:33:57,21.0,58.0,528.0,11.0,87.0,1.0,1.0,1.0,1.0,inbiot
2024-10-11 13:43:57,22.2,57.0,596.0,36.0,103.0,1.0,1.0,1.0,1.0,inbiot
2024-10-11 13:44:34,22.7,57.0,675.0,42.0,103.0,1.0,1.0,1.0,1.0,inbiot
2024-10-11 13:54:27,23.0,57.0,701.0,41.0,102.0,1.0,1.0,1.0,1.0,inbiot
...,...,...,...,...,...,...,...,...,...,...
2024-10-31 10:43:52,24.3,54.0,734.0,54.0,498.0,32.0,34.0,34.0,34.0,inbiot
2024-10-31 10:53:52,24.2,54.0,718.0,47.0,498.0,31.0,32.0,32.0,32.0,inbiot
2024-10-31 11:03:52,24.1,54.0,703.0,45.0,498.0,28.0,29.0,29.0,29.0,inbiot
2024-10-31 11:13:52,23.7,52.0,619.0,40.0,490.0,20.0,21.0,21.0,21.0,inbiot
2024-10-31 11:23:52,23.7,55.0,630.0,40.0,487.0,18.0,19.0,19.0,19.0,inbiot

In [29]:
df_inbiot.columns

Index(['temperature', 'humidity', 'co2', 'formaldehyde', 'tvoc', 'pm_1.0',
       'pm_4.0', 'pm_10', 'pm_2.5', 'sensor'],
      dtype='object')

### kaiterra

In [30]:
df_kaiterra = pd.read_csv('data/Kaiterra.csv')

df_kaiterra

,Time Point,km200.rpm10c (µg/m³),km200.rpm25c (µg/m³),km203.rtvoc (ppb),rco2 (ppm),rhumid (%),rtemp (C),Overall Index (US),Primary Pollutant
0,2024-10-11 12:42:04,6,6,0,615,56.95,22.73,25,PM2.5
1,2024-10-11 12:43:02,0,0,0,682,57.50,22.72,23,CO2
2,2024-10-11 12:44:02,0,0,0,670,57.79,22.73,22,CO2
3,2024-10-11 12:45:02,1,0,0,682,57.93,22.77,23,CO2
4,2024-10-11 12:46:02,0,0,0,682,58.18,22.82,23,CO2
...,...,...,...,...,...,...,...,...,...
28768,2024-10-31 11:22:32,51,48,11640,727,53.97,24.13,500,TVOC
28769,2024-10-31 11:23:32,50,48,12030,736,54.06,24.13,500,TVOC
28770,2024-10-31 11:24:32,56,52,12060,738,54.18,24.15,500,TVOC
28771,2024-10-31 11:25:32,52,49,12330,738,54.20,24.19,500,TVOC
28772,2024-10-31 11:26:31,51,47,12580,740,54.22,24.20,500,TVOC

#### prep

In [31]:
df_kaiterra.rename(columns={
    'km200.rpm10c (µg/m³)': 'pm_10',
    'km200.rpm25c (µg/m³)': 'pm_2.5',
    'km203.rtvoc (ppb)': 'tvoc_ppb',
    'rco2 (ppm)': 'co2',
    'rhumid (%)': 'humidity',
    'rtemp (C)': 'temperature',
    'Overall Index (US)': 'overall_index',
    'Primary Pollutant': 'primary_pollutant',
    'Time Point': 'datetime'
}, inplace=True)

df_kaiterra.set_index("datetime",inplace=True)
df_kaiterra.index = pd.to_datetime(df_kaiterra.index)
df_kaiterra.index = df_kaiterra.index + pd.Timedelta(minutes=60)

shift_condition = df_kaiterra.index >= pd.Timestamp('2024-10-27 03:00:00')
df_kaiterra.index = [time - pd.Timedelta(hours=1) if shift_condition[i] else time for i, time in enumerate(df_kaiterra.index)]

df_kaiterra["sensor"] = "kaiterra"


df_kaiterra

,pm_10,pm_2.5,tvoc_ppb,co2,humidity,temperature,overall_index,primary_pollutant,sensor
2024-10-11 13:42:04,6,6,0,615,56.95,22.73,25,PM2.5,kaiterra
2024-10-11 13:43:02,0,0,0,682,57.50,22.72,23,CO2,kaiterra
2024-10-11 13:44:02,0,0,0,670,57.79,22.73,22,CO2,kaiterra
2024-10-11 13:45:02,1,0,0,682,57.93,22.77,23,CO2,kaiterra
2024-10-11 13:46:02,0,0,0,682,58.18,22.82,23,CO2,kaiterra
...,...,...,...,...,...,...,...,...,...
2024-10-31 11:22:32,51,48,11640,727,53.97,24.13,500,TVOC,kaiterra
2024-10-31 11:23:32,50,48,12030,736,54.06,24.13,500,TVOC,kaiterra
2024-10-31 11:24:32,56,52,12060,738,54.18,24.15,500,TVOC,kaiterra
2024-10-31 11:25:32,52,49,12330,738,54.20,24.19,500,TVOC,kaiterra
2024-10-31 11:26:31,51,47,12580,740,54.22,24.20,500,TVOC,kaiterra

### LS 168

In [32]:
df_168 = pd.read_csv('data/ls_168.csv')

df_168

,timestamp(UTC),NetCO2-CO2(ppm),NetCO2-CO2_ug,NetADC_O3-O3_ug,NetADC_O3-O3(ppb),NetADC_CO-CO_ug,NetADC_CO-CO( ppb),NetPM-PM10(µg/m3),NetPM-PM25(µg/m3),NetPid_P1-PPB(ppm),NetPid_P1-PPB_ug,NetBME280-PERC(%),NetBME280-TEMP_EXT(°C),NetBME280-HPA(hPa),NetADC_NO2-NO2_ug,NetADC_NO2-NO2(ppb)
0,2024-10-01T00:00:02,435.41,777.74,110.36,56.65,101.54,89.32,5.84,5.84,0.1783,406.0460,34.52,24.79,1005.05,125.88,67.41
1,2024-10-01T00:00:07,436.38,779.48,65.85,33.80,86.15,75.78,5.91,5.91,0.1784,406.3447,34.53,24.79,1005.04,73.97,39.61
2,2024-10-01T00:00:12,436.05,778.92,88.10,45.22,91.29,80.30,5.77,5.77,0.1784,406.3096,34.53,24.79,1005.09,100.84,54.00
3,2024-10-01T00:00:17,435.85,778.53,80.44,41.29,89.57,78.79,5.59,5.59,0.1783,406.0724,34.54,24.79,1005.05,64.71,34.65
4,2024-10-01T00:00:22,436.12,779.02,87.40,44.86,111.80,98.34,5.29,5.29,0.1783,406.0920,34.53,24.79,1005.06,73.97,39.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524555,2024-10-31T10:21:52,701.84,1264.25,133.03,67.71,867.81,756.96,26.59,26.59,0.3555,816.4531,48.69,25.84,1017.11,109.17,57.97
524556,2024-10-31T10:21:57,701.49,1263.65,118.31,60.22,885.09,772.00,26.19,26.19,0.3531,810.9996,48.66,25.83,1017.11,109.17,57.97
524557,2024-10-31T10:22:02,701.01,1262.79,111.30,56.65,898.86,784.02,26.31,26.31,0.3504,804.7006,48.66,25.84,1017.14,100.77,53.51
524558,2024-10-31T10:22:07,701.18,1263.03,133.02,67.71,907.44,791.54,26.44,26.44,0.3530,810.6940,48.71,25.84,1017.09,126.94,67.41
524559,2024-10-31T10:22:12,701.24,1263.12,140.03,71.28,885.02,772.00,26.23,26.23,0.3564,818.5178,48.74,25.84,1017.07,100.77,53.51

#### prep

In [33]:
df_168.rename(columns={
    'timestamp(UTC)': 'datetime',
    'NetCO2-CO2(ppm)': 'co2',
    'NetCO2-CO2_ug': 'co2_ug',
    'NetADC_O3-O3_ug': 'o3_ug',
    'NetADC_O3-O3(ppb)': 'o3',
    'NetADC_CO-CO_ug': 'co_ug',
    'NetADC_CO-CO( ppb)': 'co',
    'NetPM-PM10(µg/m3)': 'pm_10',
    'NetPM-PM25(µg/m3)': 'pm_2.5',
    'NetPid_P1-PPB(ppm)': 'tvoc',
    'NetPid_P1-PPB_ug': 'tvoc_ug',
    'NetBME280-PERC(%)': 'humidity',
    'NetBME280-TEMP_EXT(°C)': 'temperature',
    'NetBME280-HPA(hPa)': 'pressure',
    'NetADC_NO2-NO2_ug': 'no2_ug',
    'NetADC_NO2-NO2(ppb)': 'no2',
}, inplace=True)


df_168['datetime'] = pd.to_datetime(df_168['datetime'])
df_168.set_index('datetime', inplace=True)

df_168.drop(columns=df_168.filter(like='_ug').columns, inplace=True)

df_168["sensor"] = "LS_168"
df_168.index = df_168.index + pd.Timedelta(minutes=120)

shift_condition = df_168.index >= pd.Timestamp('2024-10-27 03:00:00')
df_168.index = [time - pd.Timedelta(hours=1) if shift_condition[i] else time for i, time in enumerate(df_168.index)]

df_168.head(),df_168.tail()

(                        co2     o3     co  pm_10  pm_2.5    tvoc  humidity  \
 2024-10-01 02:00:02  435.41  56.65  89.32   5.84    5.84  0.1783     34.52
 2024-10-01 02:00:07  436.38  33.80  75.78   5.91    5.91  0.1784     34.53
 2024-10-01 02:00:12  436.05  45.22  80.30   5.77    5.77  0.1784     34.53
 2024-10-01 02:00:17  435.85  41.29  78.79   5.59    5.59  0.1783     34.54
 2024-10-01 02:00:22  436.12  44.86  98.34   5.29    5.29  0.1783     34.53

                      temperature  pressure    no2  sensor
 2024-10-01 02:00:02        24.79   1005.05  67.41  LS_168
 2024-10-01 02:00:07        24.79   1005.04  39.61  LS_168
 2024-10-01 02:00:12        24.79   1005.09  54.00  LS_168
 2024-10-01 02:00:17        24.79   1005.05  34.65  LS_168
 2024-10-01 02:00:22        24.79   1005.06  39.61  LS_168  ,
                         co2     o3      co  pm_10  pm_2.5    tvoc  humidity  \
 2024-10-31 11:21:52  701.84  67.71  756.96  26.59   26.59  0.3555     48.69
 2024-10-31 11:21:57  701.49  60.22  772.00  26.19   26.19  0.3531     48.66
 2024-10-31 11:22:02  701.01  56.65  784.02  26.31   26.31  0.3504     48.66
 2024-10-31 11:22:07  701.18  67.71  791.54  26.44   26.44  0.3530     48.71
 2024-10-31 11:22:12  701.24  71.28  772.00  26.23   26.23  0.3564     48.74

                      temperature  pressure    no2  sensor
 2024-10-31 11:21:52        25.84   1017.11  57.97  LS_168
 2024-10-31 11:21:57        25.83   1017.11  57.97  LS_168
 2024-10-31 11:22:02        25.84   1017.14  53.51  LS_168
 2024-10-31 11:22:07        25.84   1017.09  67.41  LS_168
 2024-10-31 11:22:12        25.84   1017.07  53.51  LS_168  )

### LS 169

In [34]:
df_169 = pd.read_csv('data/ls_169.csv')

df_169

,timestamp(UTC),NetCO2-CO2(ppm),NetCO2-CO2_ug,NetADC_O3-O3_ug,NetADC_O3-O3(ppb),NetADC_CO-CO_ug,NetADC_CO-CO( ppb),NetPM-PM10(µg/m3),NetPM-PM25(µg/m3),NetPid_P1-PPB(ppm),NetPid_P1-PPB_ug,NetBME280-PERC(%),NetBME280-TEMP_EXT(°C),NetBME280-HPA(hPa),NetADC_NO2-NO2_ug,NetADC_NO2-NO2(ppb)
0,2024-10-11T11:30:58,414.07,743.23,-49.55,-25.31,17302.75,15146.45,0.93,0.87,0.3725,852.4625,52.65,22.40,1001.82,-352.57,-187.89
1,2024-10-11T11:31:03,415.02,744.95,-34.73,-17.74,17237.12,15088.52,1.06,0.99,0.3472,794.6321,52.58,22.41,1001.89,-338.06,-180.15
2,2024-10-11T11:31:08,414.56,744.03,-19.91,-10.17,17250.21,15101.89,1.21,1.13,0.3224,737.7207,52.62,22.43,1001.83,-300.90,-160.37
3,2024-10-11T11:31:13,414.47,743.87,-26.64,-13.61,17219.57,15075.15,1.21,1.11,0.3037,694.9004,52.65,22.43,1001.82,-271.05,-144.46
4,2024-10-11T11:31:18,414.70,744.23,2.31,1.18,17249.23,15101.89,1.15,1.08,0.2912,666.2870,52.60,22.45,1001.84,-273.46,-145.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344728,2024-10-31T10:21:53,653.09,1177.12,108.47,55.18,930.13,810.84,25.24,25.24,0.4445,1021.3496,47.98,25.75,1017.40,78.57,41.70
344729,2024-10-31T10:21:58,652.31,1175.72,94.26,47.95,935.26,815.30,25.50,25.50,0.4396,1010.0927,47.97,25.75,1017.41,78.58,41.70
344730,2024-10-31T10:22:03,652.69,1176.33,101.02,51.39,932.63,813.07,25.98,25.98,0.4407,1012.6028,48.00,25.76,1017.38,78.57,41.70
344731,2024-10-31T10:22:08,653.13,1177.14,101.02,51.39,945.42,824.21,26.22,26.22,0.4462,1025.2487,48.04,25.76,1017.38,78.57,41.70
344732,2024-10-31T10:22:13,652.55,1176.06,108.46,55.18,924.94,806.38,26.23,26.23,0.4517,1037.8886,48.04,25.76,1017.35,78.57,41.70

#### prep

In [35]:
df_169.rename(columns={
    'timestamp(UTC)': 'datetime',
    'NetCO2-CO2(ppm)': 'co2',
    'NetCO2-CO2_ug': 'co2_ug',
    'NetADC_O3-O3_ug': 'o3_ug',
    'NetADC_O3-O3(ppb)': 'o3',
    'NetADC_CO-CO_ug': 'co_ug',
    'NetADC_CO-CO( ppb)': 'co',
    'NetPM-PM10(µg/m3)': 'pm_10',
    'NetPM-PM25(µg/m3)': 'pm_2.5',
    'NetPid_P1-PPB(ppm)': 'tvoc',
    'NetPid_P1-PPB_ug': 'tvoc_ug',
    'NetBME280-PERC(%)': 'humidity',
    'NetBME280-TEMP_EXT(°C)': 'temperature',
    'NetBME280-HPA(hPa)': 'pressure',
    'NetADC_NO2-NO2_ug': 'no2_ug',
    'NetADC_NO2-NO2(ppb)': 'no2',
}, inplace=True)


df_169['datetime'] = pd.to_datetime(df_169['datetime'])
df_169.set_index('datetime', inplace=True)

df_169.drop(columns=df_169.filter(like='_ug').columns, inplace=True)

df_169["sensor"] = "LS_169"

df_169.index = df_169.index + pd.Timedelta(minutes=120)

shift_condition = df_169.index >= pd.Timestamp('2024-10-27 03:00:00')
df_169.index = [time - pd.Timedelta(hours=1) if shift_condition[i] else time for i, time in enumerate(df_169.index)]

df_169.head(),df_169.tail()

(                        co2     o3        co  pm_10  pm_2.5    tvoc  humidity  \
 2024-10-11 13:30:58  414.07 -25.31  15146.45   0.93    0.87  0.3725     52.65
 2024-10-11 13:31:03  415.02 -17.74  15088.52   1.06    0.99  0.3472     52.58
 2024-10-11 13:31:08  414.56 -10.17  15101.89   1.21    1.13  0.3224     52.62
 2024-10-11 13:31:13  414.47 -13.61  15075.15   1.21    1.11  0.3037     52.65
 2024-10-11 13:31:18  414.70   1.18  15101.89   1.15    1.08  0.2912     52.60

                      temperature  pressure     no2  sensor
 2024-10-11 13:30:58        22.40   1001.82 -187.89  LS_169
 2024-10-11 13:31:03        22.41   1001.89 -180.15  LS_169
 2024-10-11 13:31:08        22.43   1001.83 -160.37  LS_169
 2024-10-11 13:31:13        22.43   1001.82 -144.46  LS_169
 2024-10-11 13:31:18        22.45   1001.84 -145.75  LS_169  ,
                         co2     o3      co  pm_10  pm_2.5    tvoc  humidity  \
 2024-10-31 11:21:53  653.09  55.18  810.84  25.24   25.24  0.4445     47.98
 2024-10-31 11:21:58  652.31  47.95  815.30  25.50   25.50  0.4396     47.97
 2024-10-31 11:22:03  652.69  51.39  813.07  25.98   25.98  0.4407     48.00
 2024-10-31 11:22:08  653.13  51.39  824.21  26.22   26.22  0.4462     48.04
 2024-10-31 11:22:13  652.55  55.18  806.38  26.23   26.23  0.4517     48.04

                      temperature  pressure   no2  sensor
 2024-10-31 11:21:53        25.75   1017.40  41.7  LS_169
 2024-10-31 11:21:58        25.75   1017.41  41.7  LS_169
 2024-10-31 11:22:03        25.76   1017.38  41.7  LS_169
 2024-10-31 11:22:08        25.76   1017.38  41.7  LS_169
 2024-10-31 11:22:13        25.76   1017.35  41.7  LS_169  )

### Smart sense

In [38]:
df_smart_sense = pd.read_csv('data/smart_sense.csv')

df_smart_sense

,ts[datetime],te[datetime],CO2[ppm],T[°C],RH[%],PM1[ugm3],PM2.5[ugm3],PM10[ugm3],indoor.NOx_index[idx],indoor.VOC_index[idx]
0,11/10/2024 10:47,11/10/2024 10:47,636,19.94,70.35,2.8,3.5,3.9,1.0,64.0
1,11/10/2024 10:48,11/10/2024 10:48,652,20.03,70.20,3.0,4.5,5.7,1.0,71.0
2,11/10/2024 10:49,11/10/2024 10:49,670,20.10,70.41,2.8,3.6,4.0,1.0,77.0
3,11/10/2024 10:50,11/10/2024 10:50,696,20.19,70.14,2.8,3.6,4.0,1.0,81.0
4,11/10/2024 10:51,11/10/2024 10:51,726,20.26,69.91,3.5,5.2,6.3,1.0,83.0
...,...,...,...,...,...,...,...,...,...,...
28382,31/10/2024 11:23,31/10/2024 11:23,790,23.30,56.60,14.9,23.3,25.3,2.0,459.0
28383,31/10/2024 11:24,31/10/2024 11:24,801,23.32,56.67,15.2,23.8,25.9,2.0,462.0
28384,31/10/2024 11:25,31/10/2024 11:25,799,23.36,56.72,15.0,23.5,25.5,2.0,465.0
28385,31/10/2024 11:26,31/10/2024 11:26,804,23.37,56.79,15.0,23.5,25.5,2.0,467.0
28386,31/10/2024 11:27,31/10/2024 11:27,811,23.38,56.85,14.5,22.9,25.1,2.0,470.0

#### prep

In [39]:
# Standardize column names
df_smart_sense.rename(columns={
    'ts[datetime]': 'start_time',
    'te[datetime]': 'end_time',
    'CO2[ppm]': 'co2',
    'T[°C]': 'temperature',
    'RH[%]': 'humidity',
    'indoor.NOx_index[idx]': 'nox',
    'indoor.VOC_index[idx]': 'tvoc',
    'PM1[ugm3]': 'pm_1.0',
    'PM2.5[ugm3]': 'pm_2.5',
    'PM10[ugm3]': 'pm_10',
}, inplace=True)


df_smart_sense['start_time'] = pd.to_datetime(df_smart_sense['start_time'],format="%d/%m/%Y %H:%M")
df_smart_sense['end_time'] = pd.to_datetime(df_smart_sense['end_time'],format="%d/%m/%Y %H:%M")

are_equal = df_smart_sense['end_time'].equals(df_smart_sense['end_time'])

assert are_equal == True

df_smart_sense.drop('end_time',axis=1,inplace=True)

In [40]:

df_smart_sense.set_index('start_time', inplace=True)
df_smart_sense.rename_axis('datetime', inplace=True)

df_smart_sense["sensor"] = "smart_sense"
df_smart_sense.head(),df_smart_sense.tail()

(                     co2  temperature  humidity  pm_1.0  pm_2.5  pm_10  nox  \
 datetime
 2024-10-11 10:47:00  636        19.94     70.35     2.8     3.5    3.9  1.0
 2024-10-11 10:48:00  652        20.03     70.20     3.0     4.5    5.7  1.0
 2024-10-11 10:49:00  670        20.10     70.41     2.8     3.6    4.0  1.0
 2024-10-11 10:50:00  696        20.19     70.14     2.8     3.6    4.0  1.0
 2024-10-11 10:51:00  726        20.26     69.91     3.5     5.2    6.3  1.0

                      tvoc       sensor
 datetime
 2024-10-11 10:47:00  64.0  smart_sense
 2024-10-11 10:48:00  71.0  smart_sense
 2024-10-11 10:49:00  77.0  smart_sense
 2024-10-11 10:50:00  81.0  smart_sense
 2024-10-11 10:51:00  83.0  smart_sense  ,
                      co2  temperature  humidity  pm_1.0  pm_2.5  pm_10  nox  \
 datetime
 2024-10-31 11:23:00  790        23.30     56.60    14.9    23.3   25.3  2.0
 2024-10-31 11:24:00  801        23.32     56.67    15.2    23.8   25.9  2.0
 2024-10-31 11:25:00  799        23.36     56.72    15.0    23.5   25.5  2.0
 2024-10-31 11:26:00  804        23.37     56.79    15.0    23.5   25.5  2.0
 2024-10-31 11:27:00  811        23.38     56.85    14.5    22.9   25.1  2.0

                       tvoc       sensor
 datetime
 2024-10-31 11:23:00  459.0  smart_sense
 2024-10-31 11:24:00  462.0  smart_sense
 2024-10-31 11:25:00  465.0  smart_sense
 2024-10-31 11:26:00  467.0  smart_sense
 2024-10-31 11:27:00  470.0  smart_sense  )

### ref machine

In [41]:
ref_df = pd.read_csv('data/ref_data.csv',index_col=0)
ref_df

,timestamp,averaging[s],PM1 [µg/m³],PM2.5 [µg/m³],PM4 [µg/m³],PM10 [µg/m³],PMtot [µg/m³],CO2 [ppm],VOC [mg/m³],Cn [1/cm³],...,x90(dCn) [µm],T [°C],p [hPa],rH [%],AQI-Palas,Infection Risk Index,volume flow [l/min],power (volume flow blower) [%],global error,dCn(µm) [1/cm³]
0,2024-10-11 13:02:00,48.0,0.07,0.07,0.08,0.07,0.07,498.78,0.00,1.72,...,0.29,19.37,988.80,66.20,0.71,0.00,NaN,29.77,1.0,->
1,2024-10-11 13:03:00,60.0,0.00,0.00,0.00,0.00,0.00,486.63,0.00,0.03,...,0.29,19.95,1000.70,62.43,4.22,0.00,NaN,48.00,1.0,->
2,2024-10-11 13:04:00,60.0,0.07,0.07,0.07,0.07,0.07,477.93,0.00,1.62,...,0.26,20.14,1000.70,61.50,5.00,0.00,NaN,33.03,1.0,->
3,2024-10-11 13:05:00,60.0,1.57,2.29,3.10,2.87,37.71,475.47,0.02,31.90,...,0.35,20.27,1000.70,61.19,5.00,0.03,1.46,22.25,1.0,->
4,2024-10-11 13:06:00,60.0,1.47,2.24,3.50,3.62,3.93,472.03,0.01,38.22,...,0.32,20.35,1000.70,60.84,4.40,0.03,1.37,20.02,1.0,->
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,2024-11-05 16:17:00,60.0,55.97,67.93,77.52,72.38,73.09,996.77,0.06,1112.10,...,0.34,22.17,1010.80,51.54,56.47,1.45,1.00,14.56,0.0,->
180,2024-11-05 16:18:00,60.0,56.80,67.91,77.01,71.76,107.12,1025.73,0.09,1140.10,...,0.33,22.78,1010.84,50.25,58.78,1.49,1.00,14.81,0.0,->
181,2024-11-05 16:19:00,60.0,56.13,68.23,78.86,75.24,88.45,1034.32,0.09,1142.41,...,0.33,23.02,1010.82,51.30,60.80,1.53,1.00,14.83,0.0,->
182,2024-11-05 16:20:00,60.0,56.73,68.08,75.86,82.62,110.76,1011.70,0.07,1154.18,...,0.33,23.13,1010.83,48.37,62.53,1.53,1.00,14.82,0.0,->
183,2024-11-05 16:21:00,60.0,57.75,71.41,84.25,86.55,91.76,1005.20,0.03,1176.39,...,0.33,22.68,1010.90,48.76,64.23,1.48,1.00,14.94,0.0,->

#### prep

In [42]:
rename_map = {
    'timestamp': 'timestamp',
    'averaging[s]': 'averaging',
    'PM1 [µg/m³]': 'pm_1.0',
    'PM2.5 [µg/m³]': 'pm_2.5',
    'PM4 [µg/m³]': 'pm_4.0',
    'PM10 [µg/m³]': 'pm_10',
    'PMtot [µg/m³]': 'pm_tot',
    'CO2 [ppm]': 'co2',
    'VOC [mg/m³]': 'tvoc_mg',
    'Cn [1/cm³]': 'cn',
    'M1,0 [µm]': 'm1_0',
    'M2,0 [µm²]': 'm2_0',
    'M3,0 [µm³]': 'm3_0',
    'x10(dCn) [µm]': 'x10_dcn',
    'x16(dCn) [µm]': 'x16_dcn',
    'x50(dCn) [µm]': 'x50_dcn',
    'x84(dCn) [µm]': 'x84_dcn',
    'x90(dCn) [µm]': 'x90_dcn',
    'T [°C]': 'temperature',
    'p [hPa]': 'pressure',
    'rH [%]': 'humidity',
    'AQI-Palas': 'aqi_palas',
    'Infection Risk Index': 'infection_risk_index',
    'volume flow [l/min]': 'volume_flow',
    'power (volume flow blower) [%]': 'power_volume_flow',
    'global error': 'global_error',
    'dCn(µm) [1/cm³]': 'dcn'
}

# Standardizing column names
ref_df.rename(columns=rename_map, inplace=True)

ref_df["sensor"] = "ref_sensor"

ref_df['datetime'] = pd.to_datetime(ref_df['timestamp'])

ref_df.set_index('datetime',inplace=True)
ref_df.drop('timestamp',axis=1,inplace=True)

ref_df

,averaging,pm_1.0,pm_2.5,pm_4.0,pm_10,pm_tot,co2,tvoc_mg,cn,m1_0,...,temperature,pressure,humidity,aqi_palas,infection_risk_index,volume_flow,power_volume_flow,global_error,dcn,sensor
datetime,,,,,,,,,,,,,,,,,,,,,
2024-10-11 13:02:00,48.0,0.07,0.07,0.08,0.07,0.07,498.78,0.00,1.72,0.26,...,19.37,988.80,66.20,0.71,0.00,NaN,29.77,1.0,->,ref_sensor
2024-10-11 13:03:00,60.0,0.00,0.00,0.00,0.00,0.00,486.63,0.00,0.03,0.26,...,19.95,1000.70,62.43,4.22,0.00,NaN,48.00,1.0,->,ref_sensor
2024-10-11 13:04:00,60.0,0.07,0.07,0.07,0.07,0.07,477.93,0.00,1.62,0.23,...,20.14,1000.70,61.50,5.00,0.00,NaN,33.03,1.0,->,ref_sensor
2024-10-11 13:05:00,60.0,1.57,2.29,3.10,2.87,37.71,475.47,0.02,31.90,0.30,...,20.27,1000.70,61.19,5.00,0.03,1.46,22.25,1.0,->,ref_sensor
2024-10-11 13:06:00,60.0,1.47,2.24,3.50,3.62,3.93,472.03,0.01,38.22,0.26,...,20.35,1000.70,60.84,4.40,0.03,1.37,20.02,1.0,->,ref_sensor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-11-05 16:17:00,60.0,55.97,67.93,77.52,72.38,73.09,996.77,0.06,1112.10,0.27,...,22.17,1010.80,51.54,56.47,1.45,1.00,14.56,0.0,->,ref_sensor
2024-11-05 16:18:00,60.0,56.80,67.91,77.01,71.76,107.12,1025.73,0.09,1140.10,0.27,...,22.78,1010.84,50.25,58.78,1.49,1.00,14.81,0.0,->,ref_sensor
2024-11-05 16:19:00,60.0,56.13,68.23,78.86,75.24,88.45,1034.32,0.09,1142.41,0.27,...,23.02,1010.82,51.30,60.80,1.53,1.00,14.83,0.0,->,ref_sensor
2024-11-05 16:20:00,60.0,56.73,68.08,75.86,82.62,110.76,1011.70,0.07,1154.18,0.27,...,23.13,1010.83,48.37,62.53,1.53,1.00,14.82,0.0,->,ref_sensor
2024-11-05 16:21:00,60.0,57.75,71.41,84.25,86.55,91.76,1005.20,0.03,1176.39,0.27,...,22.68,1010.90,48.76,64.23,1.48,1.00,14.94,0.0,->,ref_sensor

### thinnect

In [43]:
df_full_thinnect = pd.DataFrame()
base_dir = 'data/thinnect'

for pollutant in os.listdir(base_dir):
    df_pol = pd.DataFrame()
    
    for file in os.listdir(os.path.join(base_dir,pollutant)):
        df_mini = pd.read_csv(os.path.join(base_dir,pollutant,file),index_col=0,parse_dates=True)
        df_pol=pd.concat([df_pol,df_mini],axis=0)
   
    df_full_thinnect = pd.concat([df_full_thinnect,df_pol.resample('15min').mean()],axis=1)
    

df_full_thinnect

,TAR,VOCR,PM2.5R,O3R,PM10R,RHR,PM1.0R,CO2R
time,,,,,,,,
2024-10-11 11:30:00,22.850000,NaN,NaN,NaN,NaN,49.500000,NaN,695.000000
2024-10-11 11:45:00,23.825000,NaN,0.000000,NaN,0.000000,46.750000,0.000000,827.750000
2024-10-11 12:00:00,24.180000,NaN,0.000000,NaN,0.000000,48.000000,0.000000,1035.000000
2024-10-11 12:15:00,24.600000,NaN,0.200000,NaN,0.200000,48.000000,0.000000,1252.000000
2024-10-11 12:30:00,24.400000,NaN,0.333333,NaN,0.333333,45.833333,0.333333,988.500000
...,...,...,...,...,...,...,...,...
2024-10-31 09:15:00,25.400000,1.528000,39.666667,NaN,42.333333,54.000000,24.333333,431.000000
2024-10-31 09:30:00,25.260000,0.356000,46.000000,10.963,49.200000,52.200000,27.800000,577.200000
2024-10-31 09:45:00,25.057143,0.494667,35.333333,10.994,37.500000,50.714286,21.666667,441.285714
2024-10-31 10:00:00,25.000000,0.201000,45.000000,NaN,48.500000,52.000000,28.000000,457.000000
2024-10-31 10:15:00,24.500000,0.399667,26.666667,11.060,27.000000,51.000000,16.666667,584.000000

In [44]:
df_full_thinnect.isnull().sum()

TAR         23
VOCR       430
PM2.5R      26
O3R       1297
PM10R       26
RHR         23
PM1.0R      26
CO2R        23
dtype: int64

### prep

In [45]:
df_full_thinnect.rename(columns={
    'TAR': 'temperature',
    'VOCR': 'tvoc_mg',
    'PM2.5R': 'pm_2.5',
    'O3R': 'o3',
    'PM10R': 'pm_10',
    'RHR': 'humidity',
    'PM1.0R': 'pm_1.0',
    'CO2R': 'pm_1.0',
    
}, inplace=True)

df_full_thinnect = df_full_thinnect.rename_axis('datetime')
df_full_thinnect["sensor"] = "thinnect"

df_full_thinnect.index = df_full_thinnect.index + pd.Timedelta(minutes=120)

shift_condition = df_full_thinnect.index >= pd.Timestamp('2024-10-27 03:00:00')
df_full_thinnect.index = [time - pd.Timedelta(hours=1) if shift_condition[i] else time for i, time in enumerate(df_full_thinnect.index)]

In [46]:
df_full_thinnect.to_csv('data/thinnect_full.csv')

## Concat data in one csv

In [47]:
ref_df.columns

Index(['averaging', 'pm_1.0', 'pm_2.5', 'pm_4.0', 'pm_10', 'pm_tot', 'co2',
       'tvoc_mg', 'cn', 'm1_0', 'm2_0', 'm3_0', 'x10_dcn', 'x16_dcn',
       'x50_dcn', 'x84_dcn', 'x90_dcn', 'temperature', 'pressure', 'humidity',
       'aqi_palas', 'infection_risk_index', 'volume_flow', 'power_volume_flow',
       'global_error', 'dcn', 'sensor'],
      dtype='object')

In [48]:
df_list = [df_inbiot,df_kaiterra,df_168,df_169,df_smart_sense,ref_df]

combined_df = pd.concat(df_list, axis=0,sort=True)

combined_df.to_csv('data/clean_data/all_sensors.csv')